/**
 * Regenerate tests/fixtures/registry/ from a registry checkout.
 *
 * The fixture set is a verbatim snapshot of what the registry publishes
 * (chain.json / bridge.json / tokens.json per chain) plus one synthetic
 * chain emitted by THIS script (unknown status value) so parser tolerance
 * is exercised without hand-editing fixtures. Hand-written registry
 * fixtures are banned in this repo: they are how a dead quote path once
 * stayed green (spec "Registry is the only source of chain knowledge",
 *.
 *
 * Usage:  REGISTRY_PATH=/path/to/rome-registry npm run gen:fixtures
 */
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const REGISTRY_PATH = process.env.REGISTRY_PATH;
if (!REGISTRY_PATH) {
  console.error("REGISTRY_PATH is required (path to a rome-protocol/rome-registry checkout, synced to origin/main)");
  process.exit(1);
}
const src = resolve(REGISTRY_PATH.replace(/^~(?=\/)/, process.env.HOME ?? "~"));
const out = resolve(__dirname, "..", "tests", "fixtures", "registry");

const COPY_FILES = ["chain.json", "bridge.json", "tokens.json", "contracts.json"] as const;

rmSync(out, { recursive: true, force: true });
mkdirSync(join(out, "chains"), { recursive: true });

const chainDirs = readdirSync(join(src, "chains"), { withFileTypes: true })
  .filter((e) => e.isDirectory())
  .map((e) => e.name)
  .sort();

let copied = 0;
for (const slug of chainDirs) {
  for (const f of COPY_FILES) {
    const p = join(src, "chains", slug, f);
    if (!existsSync(p)) continue;
    mkdirSync(join(out, "chains", slug), { recursive: true });
    cpSync(p, join(out, "chains", slug, f));
    copied++;
  }
}
cpSync(join(src, "programs", "index.json"), join(out, "programs", "index.json"), { recursive: true });

// Synthetic tolerance case: a chain whose status value this repo has never
// seen. listChains must SKIP it (not throw) — future registry status values
// must not take the whole endpoint down.
const synthSlug = "999999-synthetic-unknown-status";
mkdirSync(join(out, "chains", synthSlug), { recursive: true });
writeFileSync(
  join(out, "chains", synthSlug, "chain.json"),
  JSON.stringify(
    {
      chainId: 999999,
      name: "Synthetic Unknown Status (generated by gen-registry-fixtures.ts)",
      network: "devnet",
      status: "preparing",
      rpcUrl: "https://synthetic.invalid",
    },
    null,
    2,
  ) + "\n",
);

const git = (cmd: string) => execSync(`git -C ${src} ${cmd}`, { encoding: "utf8" }).trim();
const manifest = {
  source: "rome-protocol/rome-registry",
  gitSha: git("rev-parse HEAD"),
  gitDescribe: git("log -1 --format=%cI"),
  registryVersion: JSON.parse(readFileSync(join(src, "package.json"), "utf8")).version as string,
  generatedAt: new Date().toISOString(),
  generator: "scripts/gen-registry-fixtures.ts",
  chains: chainDirs,
  synthetic: [synthSlug],
};
writeFileSync(join(out, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");
console.log(`fixtures: ${copied} files across ${chainDirs.length} chains (+1 synthetic) @ registry ${manifest.registryVersion} ${manifest.gitSha.slice(0, 12)}`);
